--[[
Garrison-related enumerations

The API does not return information about the building type, even less in a localization & faction independent way, so match
the building id's with an internal value.
--]]

local enum = DataStore.Enum

enum.BuildingTypes = {
	TownHall = 0,
	AlchemyLab = 1,
	Barn = 2,
	Barracks = 3,
	DwarvenBunker = 4,
	EnchantersStudy = 5,
	EngineeringWorks = 6,
	FishingShack = 7,
	GemBoutique = 8,
	GladiatorsSanctum = 9,
	GnomishGearworks = 10,
	HerbGarden = 11,
	LumberMill = 12,
	LunarfallExcavation = 13,
	LunarfallInn = 14,
	MageTower = 15,
	Menagerie = 16,
	SalvageYard = 17,
	ScribesQuarters = 18,
	Stables = 19,
	Storehouse = 20,
	TailoringEmporium = 21,
	TheForge = 22,
	TheTannery = 23,
	TradingPost = 24,
}

local types = enum.BuildingTypes

enum.BuildingIDToTypes = {
	[76] = types.AlchemyLab,
	[119] = types.AlchemyLab,
	[120] = types.AlchemyLab,
	[24] = types.Barn,
	[25] = types.Barn,
	[133] = types.Barn,
	[26] = types.Barracks,
	[27] = types.Barracks,
	[28] = types.Barracks,
	[8] = types.DwarvenBunker,
	[9] = types.DwarvenBunker,
	[10] = types.DwarvenBunker,
	[93] = types.EnchantersStudy,
	[125] = types.EnchantersStudy,
	[126] = types.EnchantersStudy,
	[91] = types.EngineeringWorks,
	[123] = types.EngineeringWorks,
	[124] = types.EngineeringWorks,
	[64] = types.FishingShack,
	[134] = types.FishingShack,
	[135] = types.FishingShack,
	[96] = types.GemBoutique,
	[131] = types.GemBoutique,
	[132] = types.GemBoutique,
	[159] = types.GladiatorsSanctum,
	[160] = types.GladiatorsSanctum,
	[161] = types.GladiatorsSanctum,
	[162] = types.GnomishGearworks,
	[163] = types.GnomishGearworks,
	[164] = types.GnomishGearworks,
	[29] = types.HerbGarden,
	[136] = types.HerbGarden,
	[137] = types.HerbGarden,
	[40] = types.LumberMill,
	[41] = types.LumberMill,
	[138] = types.LumberMill,
	[61] = types.LunarfallExcavation,
	[62] = types.LunarfallExcavation,
	[63] = types.LunarfallExcavation,
	[34] = types.LunarfallInn,
	[35] = types.LunarfallInn,
	[36] = types.LunarfallInn,
	[37] = types.MageTower,
	[38] = types.MageTower,
	[39] = types.MageTower,
	[42] = types.Menagerie,
	[167] = types.Menagerie,
	[168] = types.Menagerie,
	[52] = types.SalvageYard,
	[140] = types.SalvageYard,
	[141] = types.SalvageYard,
	[95] = types.ScribesQuarters,
	[129] = types.ScribesQuarters,
	[130] = types.ScribesQuarters,
	[65] = types.Stables,
	[66] = types.Stables,
	[67] = types.Stables,
	[51] = types.Storehouse,
	[142] = types.Storehouse,
	[143] = types.Storehouse,
	[94] = types.TailoringEmporium,
	[127] = types.TailoringEmporium,
	[128] = types.TailoringEmporium,
	[60] = types.TheForge,
	[117] = types.TheForge,
	[118] = types.TheForge,
	[90] = types.TheTannery,
	[121] = types.TheTannery,
	[122] = types.TheTannery,
	[111] = types.TradingPost,
	[144] = types.TradingPost,
	[145] = types.TradingPost,
}
